FROM sogis/gretl-runtime:latest

USER root

RUN yum install -y nc

WORKDIR /tmp

COPY tests/testscript.sh /tmp/
COPY tests/build.gradle /tmp/
COPY tests/*.sql /tmp/
COPY tests/*.itf /tmp/

USER 1001

ENTRYPOINT ["/bin/sh"]

CMD ["-c", "/tmp/testscript.sh"]
